import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Bebas_Neue } from 'next/font/google'
import './globals.css'

const acta = localFont({
  weight: '400',
  src: './fonts/Acta-Regular.woff',
  variable: '--font-acta',
})
const actaBold = localFont({
  weight: '700',
  src: './fonts/Acta-Bold.woff',
  variable: '--font-acta-bold',
})
const bonnieCondensedBold = localFont({
  src: './fonts/BonnieCondensed-Bold.woff',
  variable: '--font-bonnie-condensed-bold',
})
const bebasNeue = Bebas_Neue({
  weight: '400',
  variable: '--font-bebas-neue',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${acta.variable} ${actaBold.variable} ${bebasNeue.variable} ${bonnieCondensedBold.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
